/* This file was generated by syncqt. */
#ifndef QT_QTWEBKIT_VERSION_H
#define QT_QTWEBKIT_VERSION_H

#define QTWEBKIT_VERSION_STR "5.4.2"

#define QTWEBKIT_VERSION 0x050402

#endif // QT_QTWEBKIT_VERSION_H
